### ISSUE TITLE
consume postgres operator for managing db

### ISSUE THREAD

**Issue by skattoju** [opdev/l5-operator-demo#3] opened 2021-12-21 19:48 UTC
install postgres operator / crunchy
read / familiarize with operator functionality

**Comment by skattoju** [comment] 2022-01-25 20:06
needs to be added to dependencies.yaml install through olm was not working to be investigated

**Comment by rocrisp** [comment] 2022-02-01 16:39
Duplicate of #13

**Closed by rocrisp** 2022-02-01 16:39 UTC
